name: Check Flutter Version

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-flutter-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-tags: "true"
          fetch-depth: 0
          ref: master

      - name: Get latest stable Flutter version
        id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get versions
        id: get-versions
        run: |
          echo CURRENT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1)) >> $GITHUB_OUTPUT
          echo LATEST_TAG=${{ steps.flutter-action.outputs.VERSION }} >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare-versions
        uses: madhead/semver-utils@latest
        with:
          # A version to work with
          version: ${{ steps.get-versions.outputs.LATEST_TAG }}
          # A version to compare against
          compare-to: ${{ steps.get-versions.outputs.CURRENT_TAG }}

      - name: Establish version, revision and date
        if: ${{ steps.compare-versions.outputs.comparison-result == '>' }}
        run: |
          echo Newer stable flutter version found
          framework_line=$(echo "$(flutter --version)" | grep "Framework")  
          revision=$(echo "$framework_line" | sed -E 's/.*revision ([^ ]+).*/\1/')
          date=$(echo "$framework_line" | sed -E 's/.*([0-9]{4})-([0-9]{2})-([0-9]{2}).*/\1-\2-\3/')
          echo "Current tag is ${{ steps.get-versions.outputs.CURRENT_TAG }}"
          echo "Latest tag is ${{ steps.get-versions.outputs.LATEST_TAG }} | Revision: $revision | Date: $date"
          sed -i "s/ENV FLUTTER_VERSION=.*/ENV FLUTTER_VERSION=\"${{ steps.get-versions.outputs.LATEST_TAG }}\"/" Dockerfile

      - name: Create Pull Request
        if: ${{ steps.compare-versions.outputs.comparison-result == '>' }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update to ${{ steps.get-versions.outputs.LATEST_TAG }}
          title: Update to ${{ steps.get-versions.outputs.LATEST_TAG }}
          body: |
            - Auto-generated by create-pull-request
          branch: feature/${{ steps.get-versions.outputs.LATEST_TAG }}
