name: Check Flutter Version

# on:
#   schedule:
#     - cron: "0 0 * * *"

on:
  pull_request:
    branches:
      - master

jobs:
  check-flutter-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-tags: "true"
          fetch-depth: 0

      - name: Get latest stable Flutter version
        id: flutter-version
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get latest tag
        id: latest-tag
        run: echo CURRENT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))

      - name: Compare versions
        id: compare-versions
        run: echo LATEST_VERSION=${{ steps.flutter-action.outputs.VERSION }}
      - name: Create pull request if necessary
        if: ${{ steps.compare-versions.outputs.is-lower == 'True' }}
        run: echo current flutter version is higher
