name: Check Flutter Version

# on:
#   schedule:
#     - cron: "0 0 * * *"

on:
  pull_request:
    branches:
      - master

jobs:
  check-flutter-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-tags: "true"
          fetch-depth: 0

      - name: Get latest stable Flutter version
        id: flutter-action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get versions
        id: get-versions
        run: |
          echo CURRENT_TAG=$(git describe --tags $(git rev-list --tags --max-count=1)) >> $GITHUB_OUTPUT
          echo LATEST_TAG=${{ steps.flutter-action.outputs.VERSION }} >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare-versions
        run: |
          echo current tag: ${{ steps.get-versions.outputs.CURRENT_TAG }} 
          echo latest tag: ${{ steps.get-versions.outputs.LATEST_TAG }}

      - name: Create pull request if necessary
        if: ${{ steps.compare-versions.outputs.is-lower == 'True' }}
        run: echo current flutter version is higher
